### ISSUE TITLE
Create manifest for ms sequences

### ISSUE THREAD

**Issue by mackenziekbrooks** [SteveWLU/hda#16]

**Comment by mackenziekbrooks** [comment]
See mkbmanifest.json for example. Create one for each manuscript. Use `{% if page.sigla == 'P' %}` style if statement on `/layouts/facsimile.md` to implement.

**Comment by SteveWLU** [comment]
DONE! Created manifest for each MS, replaced 'mkbmanifest.json' path in all layouts, wrote if statements for facsimile.md. Checked and works.
