### ISSUE TITLE
Link to occitan database in bibliography doesn't work

### ISSUE THREAD

**Issue by LZMorgan** [SteveWLU/hda#39]
When I formatted the Bibliography, all the links worked, but I tried the Occitan one the other day and now it does not. Address is www.dom-en-ligne.de/index.html. I get to it by typing in the address line: http://www.dom-en-ligne.de/index.html
I'm not sure what the problem is. (I typed it without the "http://"). Looking at the element, it looks correct, but maybe one must put the http:// in there to make it work?
Thanks!
Leslie

**Comment by SteveWLU** [comment]
Thanks for catching this, Leslie! I just fixed it and it should now work. 

Steve

**Comment by LZMorgan** [comment]
Thanks Steve! We can talk about how to handle bibliographical updates later. Leslie

Leslie Zarker Morgan

________________________________
From: Stephen P. McCormick ***@***.***>
Sent: Wednesday, March 24, 2021 8:47:16 AM
To: SteveWLU/hda ***@***.***>
Cc: Leslie Morgan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [SteveWLU/hda] Link to occitan database in bibliography doesn't work (#39)


Sender is external to Loyola


Thanks for catching this, Leslie! I just fixed it and it should now work.

Steve
